name: Java CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Test on java-version ${{ matrix.java-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        java-version: [1.8, 9, 10, 11, 12, 13]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Gradle build on ${{ matrix.java-version }}
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./gradlew check
          ./gradlew runFunctionalTest
      - name: Gradle build on ${{ matrix.java-version }}
        if: matrix.os == 'windows-latest'
        run: |
          $Env:Path += ';.'
          gradlew.bat runFunctionalTest

